apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - mock-rollfuse-api-configmap.yaml
  - mock-rollfuse-api-deployment.yaml
  - mock-rollfuse-api-service.yaml
  - checkout-secret.yaml
  - checkout-deployment.yaml
  - checkout-service.yaml
